# Books {#sec-ap1}

Just as there is no teaching material specifically focused on digital book history, there are no books on this subject either. Once again, we can only recommend books on related topics.

* Arnold, Taylor, and Lauren Tilton. 2015. _Humanities Data in R: Exploring Networks, Geospatial Data, Images, and Text._ Springer International Publishing. ISBN 978-3-319-20702-5 (Quantitative Methods in the Humanities and Social Sciences)
* Bilbro, Rebecca, Tony Ojeda, and Benjamin Bengfort. 2018. _Applied Text Analysis with Python._ 1st edition. O’Reilly Media, Inc. ISBN 978-1-4919-6303-6
* Gavin, Michael. 2023. _Literary Mathematics: Quantitative Theory for Textual Studies._ Stanford University Press. ISBN 978-1-5036-3282-0 (Stanford Text Technologies.)
* Gonzales, Brighid M. 2020. _Systems Librarianship: A Practical Guide for Librarians._ Bloomsbury Publishing. ISBN 979-8-8818-7951-8 (Practical Guides for Librarians)
* Gooding, Paul, Melissa M. Terras, and Sarah Ames, eds. 2025. _Library Catalogues as Data: Research, Practice and Usage._ Facet Publishing. ISBN 978-1-78330-658-9
* Klinke, Harald. 2025. _Cultural Data Science: An Introduction to R._ Springer Nature Switzerland. ISBN 978-3-031-88130-5. (Quantitative Methods in the Humanities and Social Sciences)
* Manovich, Lev. 2020. _Cultural Analytics._ The MIT Press. ISBN 978-0-262-03710-5
* Karsdorp, Folgert, Mike Kestemont, and Allen Riddell. 2021. _Humanities Data Analysis: Case Studies with Python._ Princeton University Press. ISBN 978-0-691-17236-1
* Crymble, Adam. 2021. _Technology and the Historian: Transformations in the Digital Age._ University of Illinois Press. ISBN 978-0-252-08569-7 (Topics in the Digital Humanities)
* Jockers, Matthew L., and Rosamond Thalken. 2020. _Text Analysis with R: For Students of Literature._ Springer International Publishing. ISBN 978-3-030-39643-5 (Quantitative Methods in the Humanities and Social Sciences)
* Nelson, Catherine. 2024. _Software Engineering for Data Scientists: From Notebooks to Scalable Systems._ O’Reilly. ISBN 978-1-0981-3620-8
